[project]
name = "flumut_gui"
dynamic = ["version"]
dependencies = [
    "pyqt5",
    "flumut @ git+https://github.com/izsvenezie-virology/FluMut"
]

[project.scripts]
flumut_gui = "flumut_gui:launch"

[tool.setuptools.dynamic]
version = {attr = "flumut_gui.__version__"}
