[project]
name = "mutfinder_gui"
dynamic = ["version"]
dependencies = [
    "pyqt5"
]

[project.scripts]
mutfinder_gui = "mutfinder_gui:launch"

[tool.setuptools.dynamic]
version = {attr = "mutfinder_gui.__version__"}